coordimap:
  api_key: ${BLOOPI_API_KEY}
  skip_fields:
    - secret_access_key
    - access_key_id
    - db_pass
  data_sources:
    # - type: gcp
    #   id: gcp_id_123
    #   config:
    #     - name: in_cloud
    #       value: "false"
    #     - name: credentials_file
    #       value: "/sources/pe/ny/terraform/gcp/keys/preisenergiecloud-terraform-eg.json"
    #     - name: project_id
    #       value: "PreisenergieCloud"
    #     - name: crawl_interval
    #       value: 30s
    #     - name: gcp_flows
    #       value: "true"
    #     - name: external_mappings
    #       value: europe-west3-pe-gke-cluster@kubeID123
    # - type: gcp_flow_logs
    #   id: gcp_id_123
    #   config:
    #     - name: in_cloud
    #       value: "false"
    #     - name: credentials_file
    #       value: "/sources/pe/ny/terraform/gcp/keys/preisenergiecloud-terraform-eg.json"
    #     - name: project_id
    #       value: "preisenergiecloud"
    #     - name: crawl_interval
    #       value: 30s
    # - type: aws
    #   id: awstestid
    #   config:
    #     - name: policy_config
    #       value: "true"
    #     - name: access_key_id
    #       value: ${ACCESS_KEY_ID}
    #     - name: secret_access_key
    #       value: ${SECRET_ACCSS_KEY}
    #     - name: crawl_interval
    #       value: 30s
    # - type: postgres
    #   id: postgres123
    #   name: Goldenstate-Prod
    #   desc: "This is the Goldenstate Prod DB."
    #   config:
    #     - name: db_name
    #       value: goldenstate_db
    #     - name: db_host
    #       value: "34.89.234.215"
    #     - name: db_user
    #       value: info_schema_reader
    #     - name: db_pass
    #       value: dbSchema_metadata_pwd_1@
    #     - name: ssl_mode
    #       value: require
    #     - name: crawl_interval
    #       value: 30s
    #     - name: mapping_data_source_id
    #       value: dsid_12341234
    #     - name: mapping_internal_id
    #       value: europe-west3/db-name, DBArn, namespace-db-service
    # - type: mariadb
    #   id: "data_source_123"
    #   config:
    #     - name: db_name
    #       value: mydatabase
    #     - name: db_host
    #       value: localhost
    #     - name: db_user
    #       value: root
    #     - name: db_pass
    #       value: password
    #     - name: crawl_interval
    #       value: 30s
    # - type: postgres
    #   name: post1
    #   desc: desc1
    #   config:
    #     - name: db_name
    #       value: dbname1
    #     - name: db_host
    #       value: host1
    #     - name: db_user
    #       value: user1
    #     - name: db_pass
    #       value: pass1
    #     - name: crawl_interval
    #       value: 30s
    # - type: postgres
    #   name: post2
    #   desc: desc2
    #   config:
    #     - name: db_name
    #       value: asset_repository
    #     - name: db_host
    #       value: localhost
    #     - name: db_user
    #       value: assetrepository_admin
    #     - name: db_pass
    #       value: assetrepository_pwd
    #     - name: crawl_interval
    #       value: 30s
    # - type: kubernetes
    #   # name: kube1
    #   # desc: desc1
    #   id: 123aasd
    #   config:
    #     - name: in_cluster
    #       value: "false"
    #     # - name: prometheus_host
    #     #   value: "http://localhost:9090"
    #     # - name: retina_prometheus
    #     # value: "http://localhost:9090"
    #     - name: cluster_name
    #       value: pe
    #     - name: cloud_data_source_id
    #       value: gcp-12345678
    #     - name: config_file
    #       value: /home/ermalguni/.kube/config
    #     - name: crawl_interval
    #       value: 30s
    # - type: aws_flow_logs
    #   name: flowlog1
    #   desc: desc1
    #   config:
    #   - name: log_format
    #     value: all
    #   - name: log_type
    #     value: S3
    #   - name: account_id
    #     value: 123456789
    #   - name: bucket_name
    #     value: pe-flowlogs
    #   - name: region
    #     value: eu-central-1
    #   - name: access_key_id
    #     value: ${ACCESS_KEY_ID}
    #   - name: secret_access_key
    #     value: ${SECRET_ACCSS_KEY}
    #   - name: crawl_interval
    #     value: 30s
    # - type: mongodb
    #   name: mongo-atlas-test
    #   desc: desc1
    #   config:
    #   - name: db_name
    #     value: "*"
    #   - name: db_host
    #     value: cmtest.f54q5l9.mongodb.net
    #   - name: db_user
    #     value: nodebbadmin
    #   - name: db_pass
    #     value: mF56n99dyPKBC42
    #   - name: crawl_interval
    #     value: 30s
    - type: flows
      id: "ebpf_flows"
      config:
        - name: crawl_interval
          value: 30s
        - name: deployedAt
          value: kubernetes
        - name: external_mappings
          value: "my-k8s-cluster@123aasd"
        - name: interface_name
          value: "eth0"
